config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#homepage'

get 'homepage', to: 'pages#homepage'
get 'aboutme', to: 'pages#aboutme'
get 'interests', to: 'pages#interests'
get 'study', to: 'pages#study'

get 'inquiry' => 'inquiry#index'              # 入力画面
post 'inquiry/confirm' => 'inquiry#confirm'   # 確認画面
post 'inquiry/thanks' => 'inquiry#thanks'     # 送信完了画面

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/inquiry.rb
class ContactForm < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :file,      :attachment => true

  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "My Contact Form",
      :to => "kasumi0201@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def homepage

  end

  def study

  end

  def interests

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_nav.html.erb
<div class="title">
  <img id ="logo"src="/assets/logo2.png" alt="logo">
  <head>Kasumi's Portfolio</head>
</div>

<div class="navbar">
  <ul class="nav justify-content-center">
    <li class="nav-item">
      <%= link_to 'homepage', homepage_path%>
    </li>
    </li>
    <li class="nav-item">
      <%= link_to 'study', study_path%>
    </li>
    <li class="nav-item">
      <%= link_to 'interests', interests_path%>
    </li>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio3</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= favicon_link_tag('favicon.ico') %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application','data-turbolinks-track': 'reload' %>


  </head>

  <body>
    <%= render "layouts/nav"%>

    <%= yield %>


  </body>
</html>

app/views/pages/_body.html.erb
<body>

	<input type="checkbox" class="check push" id="checked-push">
	<label class="switch push" for="checked-push"></label>

	<div class="gatefold">
	</div>

	<header class="header">
		<h1 >Hi, my name is Kasumi</h1>

		<img id ="maiko"src="/assets/maiko.jpg" alt="maiko">
	</header>
		<main class="contents">
		<h2>I am university student</br>and majoring in Chinese.</h2>
		<img class ="snip1352"src="/assets/doshisha.jpg" alt="">
		<h3>I am learning</br>programming in Sydney.</h3>
		<img class="snip1352" src="/assets/pc.jpg" alt=""></br>

		<h3>How to describe me...?</h3></br>
		<img class="snip1352" src="/assets/personality.png" alt="">


			<section class="contents__inner">
				<pre><div class="text1"><p>CONTACT:</p><p>Kasumi Takeshima</br>kasumi0201@gmail.com</p></div></pre>
			</section>
		</main>

		<footer class="footer">
			<a href="https://www.linkedin.com/in/kasumi-takeshima-7a06b8147"><img class ="linkedin" src="/assets/Linkedin.svg.png" alt=""></a>
			<a href="https://github.com/kasumi0201"><img class ="github"src="/assets/github.svg" alt=""></a>
			<a href="https://twitter.com/kasumikanzume/"><img class ="twitter"src="/assets/twitter.svg" alt=""></a>
			<a href="https://www.facebook.com/kasumi.takeshima"><img class ="facebook"src="/assets/facebook.svg.png" alt=""></a>
			<a href="https://www.instagram.com/kasumikanzume/?hl=ja"><img class ="instagram"src="/assets/insta.svg.png" alt=""></a>
		</footer>

</body>

app/views/pages/homepage.html.erb
<%= render "pages/body" %>

app/views/pages/interests.html.erb
<div class="contents">
  <img class ="snip1352" src="/assets/tra.png" alt="">
  <img class ="snip1352" src="/assets/bsk.png" alt="">
  <img class ="snip1352" src="/assets/cho.png" alt="">
  <img class ="snip1352" src="/assets/div.jpg" alt="">
</div>

app/views/pages/study.html.erb
<div class="text2">
<p>I am learning these...</p>
</div>
<div class="contents">
<img class ="snip1352" src="/assets/html5.jpg" alt="">
<img class ="snip1352" src="/assets/css.png" alt="">
<img class ="snip1352" src="/assets/ruby.png" alt="">
</div>